### ISSUE TITLE
Loses cursor after drawing canvas

### ISSUE THREAD

**Issue by jwrightecs** [saiftynet/Term-Graille#2]
After drawing the canvas made by Term::Graille, the cursor is lost/becomes invisible, running clearScreen / clear doesn't restore it, need to run 'tput cnorm' to restore (or 'reset' also works).    

Cursor is lost in the console, xterm, konsole, xfce-terminal

Seems to be the use of 
   my $blit="\033[?25l"
in printAt in Graille.pm, with no \033[?25h to restore it

**Comment by saiftynet** [comment]
Thank you for that,  will change it.

**Comment by saiftynet** [comment]
Closed in v0.06 with credit in CHANGELOG
